// ferray-stride-tricks: Runtime overlap detection for safe as_strided
//
// Determines whether a given (shape, strides) pair produces overlapping
// memory accesses. Two distinct logical indices overlap when they map to
// the same physical offset from the base pointer.

/// Check whether a view described by `shape` and `strides` (in element
/// units) would access any element of the underlying buffer more than once.
///
/// Returns `true` if the strides produce overlapping accesses (i.e., two
/// distinct multi-dimensional indices map to the same memory offset).
///
/// The algorithm works by computing the set of all physical offsets
/// reachable from the origin and checking for duplicates. For very large
/// views this could be expensive, but it is the only correct approach for
/// arbitrary stride patterns.
///
/// # Arguments
/// * `shape` — the shape of the desired view.
/// * `strides` — strides in units of elements (may be negative).
/// * `total_elements` — total number of elements in the source buffer,
///   used only as a hint; the overlap check itself is purely offset-based.
pub fn has_overlapping_strides(shape: &[usize], strides: &[isize]) -> bool {
    debug_assert_eq!(shape.len(), strides.len());

    let ndim = shape.len();

    // Zero-dimensional or empty: no overlap possible.
    if ndim == 0 || shape.contains(&0) {
        return false;
    }

    // Total number of distinct logical indices.
    let n_elements: usize = shape.iter().product();

    // A single element can't overlap with itself.
    if n_elements <= 1 {
        return false;
    }

    // If any stride is 0, that dimension is broadcast (the same element is
    // accessed for every index along that axis). This immediately means
    // overlap unless that dimension has size <= 1.
    for (i, &s) in strides.iter().enumerate() {
        if s == 0 && shape[i] > 1 {
            return true;
        }
    }

    // For moderate sizes, enumerate all offsets and check uniqueness.
    // We use a HashSet for O(1) amortised lookup.
    if n_elements <= 1_000_000 {
        return has_overlapping_enumerate(shape, strides, n_elements);
    }

    // For very large views, fall back to the same enumeration but accept
    // the cost. In practice, as_strided is seldom called with > 1M elements
    // in the safe variant.
    has_overlapping_enumerate(shape, strides, n_elements)
}

/// Enumerate all offsets and check for duplicates.
fn has_overlapping_enumerate(shape: &[usize], strides: &[isize], n_elements: usize) -> bool {
    use std::collections::HashSet;

    let ndim = shape.len();
    let mut seen = HashSet::with_capacity(n_elements);

    // We iterate in row-major order using a counter vector.
    let mut index = vec![0usize; ndim];

    for _ in 0..n_elements {
        // Compute the physical offset for the current index.
        let offset: isize = index
            .iter()
            .zip(strides.iter())
            .map(|(&idx, &stride)| idx as isize * stride)
            .sum();

        if !seen.insert(offset) {
            return true;
        }

        // Increment the multi-index (row-major order: last axis increments first).
        let mut carry = true;
        for d in (0..ndim).rev() {
            if carry {
                index[d] += 1;
                if index[d] >= shape[d] {
                    index[d] = 0;
                    // carry remains true
                } else {
                    carry = false;
                }
            }
        }
    }

    false
}

/// Validate that all offsets generated by `(shape, strides)` lie within
/// `[0, buf_len)` when measured from the base pointer.
///
/// Returns `true` if all offsets are in bounds, `false` otherwise.
pub fn all_offsets_in_bounds(shape: &[usize], strides: &[isize], buf_len: usize) -> bool {
    let ndim = shape.len();

    if ndim == 0 || shape.contains(&0) {
        return true;
    }

    // Compute the minimum and maximum offsets reachable.
    let mut min_offset: isize = 0;
    let mut max_offset: isize = 0;

    for i in 0..ndim {
        if shape[i] == 0 {
            continue;
        }
        let extent = (shape[i] as isize - 1) * strides[i];
        if extent > 0 {
            max_offset += extent;
        } else {
            min_offset += extent;
        }
    }

    // The offsets must all be non-negative and less than buf_len.
    min_offset >= 0 && max_offset >= 0 && (max_offset as usize) < buf_len
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_overlap_contiguous_1d() {
        // [0, 1, 2, 3, 4] — shape (5,), stride (1,)
        assert!(!has_overlapping_strides(&[5], &[1]));
    }

    #[test]
    fn no_overlap_contiguous_2d() {
        // 3x4 row-major: stride (4, 1)
        assert!(!has_overlapping_strides(&[3, 4], &[4, 1]));
    }

    #[test]
    fn overlap_broadcast_stride_zero() {
        // stride 0 on a dimension > 1 means overlap
        assert!(has_overlapping_strides(&[3, 4], &[0, 1]));
    }

    #[test]
    fn overlap_sliding_window() {
        // sliding window of size 3 over 5 elements: shape (3, 3), strides (1, 1)
        assert!(has_overlapping_strides(&[3, 3], &[1, 1]));
    }

    #[test]
    fn no_overlap_strided_non_contiguous() {
        // Take every other element: shape (3,), stride (2,) from buffer of 6
        assert!(!has_overlapping_strides(&[3], &[2]));
    }

    #[test]
    fn no_overlap_empty() {
        assert!(!has_overlapping_strides(&[0], &[1]));
        assert!(!has_overlapping_strides(&[3, 0], &[1, 1]));
    }

    #[test]
    fn no_overlap_scalar() {
        assert!(!has_overlapping_strides(&[1], &[1]));
        assert!(!has_overlapping_strides(&[1, 1], &[1, 1]));
    }

    #[test]
    fn overlap_negative_strides() {
        // shape (3,), stride (-1,): offsets are 0, -1, -2 — all distinct,
        // but they go negative. However for overlap detection we only care
        // about distinct vs. duplicate offsets.
        assert!(!has_overlapping_strides(&[3], &[-1]));
    }

    #[test]
    fn bounds_check_contiguous() {
        assert!(all_offsets_in_bounds(&[5], &[1], 5));
        assert!(!all_offsets_in_bounds(&[5], &[1], 4));
    }

    #[test]
    fn bounds_check_2d() {
        // 3x4, strides (4,1), buf_len=12
        assert!(all_offsets_in_bounds(&[3, 4], &[4, 1], 12));
        assert!(!all_offsets_in_bounds(&[3, 4], &[4, 1], 11));
    }

    #[test]
    fn bounds_check_empty() {
        assert!(all_offsets_in_bounds(&[0], &[1], 0));
    }

    #[test]
    fn bounds_check_negative_stride_out_of_bounds() {
        // Negative strides would go below 0
        assert!(!all_offsets_in_bounds(&[3], &[-1], 3));
    }
}
