/// Oracle test framework for validating ferray against NumPy fixture outputs.
///
/// Loads JSON fixtures generated by `scripts/generate_fixtures.py`, parses
/// array data (f64, f32, complex, bool, string), constructs ferray arrays,
/// and compares outputs using ULP (Units in the Last Place) tolerances.
use ferray_core::Array;
use ferray_core::dimension::IxDyn;
use ferray_core::error::FerrayResult;
use num_complex::Complex;
use serde::Deserialize;
use std::path::{Path, PathBuf};

// Re-export serde_json::Value so test files can use it without adding serde_json
pub use serde_json;

/// Minimum ULP tolerance applied to all oracle comparisons.
///
/// Pure-Rust implementations (faer, rustfft, serde_json) may round differently
/// from the C/Fortran stack NumPy uses (LAPACK, pocketfft, cpython json) on
/// the last few bits. 128 ULP on f64 still guarantees ~15.1 correct decimal
/// digits — well beyond any scientific measurement precision.
///
/// Note: in several cases (polyfit, roots) ferray's iterative refinement
/// produces answers *closer to mathematical truth* than NumPy's. The
/// tolerance must accommodate divergence in both directions — ferray being
/// less precise than NumPy AND ferray being more precise than NumPy (where
/// the fixture records NumPy's slightly imprecise result as "expected").
pub const MIN_ULP_TOLERANCE: u64 = 128;

// ---------------------------------------------------------------------------
// JSON schema types
// ---------------------------------------------------------------------------

/// Top-level structure of a fixture JSON file.
#[derive(Debug, Deserialize)]
pub struct FixtureSuite {
    /// The NumPy function name (e.g., "numpy.sin").
    pub function: String,
    /// The ferray function path (e.g., "ferray_ufunc::sin").
    pub ferray_function: String,
    /// Individual test cases with inputs, expected outputs, and tolerances.
    pub test_cases: Vec<TestCase>,
}

/// A single test case within a fixture file.
#[derive(Debug, Deserialize)]
pub struct TestCase {
    /// Descriptive name (e.g., "standard_f64", "special_values").
    pub name: String,
    /// Input parameters as a JSON object. Keys vary by function.
    pub inputs: serde_json::Value,
    /// Expected output.
    pub expected: serde_json::Value,
    /// Maximum allowed ULP distance between actual and expected.
    pub tolerance_ulps: u64,
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

/// Load a fixture suite from a JSON file.
pub fn load_fixture(path: &Path) -> FixtureSuite {
    let contents = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("failed to read fixture file {}: {e}", path.display()));
    serde_json::from_str(&contents)
        .unwrap_or_else(|e| panic!("failed to parse fixture JSON {}: {e}", path.display()))
}

/// Return the path to the workspace `fixtures/` directory.
///
/// Works from any crate in the workspace by walking up from `CARGO_MANIFEST_DIR`.
pub fn fixtures_dir() -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = Path::new(&manifest);
    // Walk up to find the fixtures dir (handles both crate and workspace root)
    let mut dir = manifest_path;
    loop {
        let candidate = dir.join("fixtures");
        if candidate.is_dir() {
            return candidate;
        }
        dir = match dir.parent() {
            Some(p) => p,
            None => panic!(
                "could not find fixtures/ directory from {}",
                manifest_path.display()
            ),
        };
    }
}

// ---------------------------------------------------------------------------
// JSON data parsing
// ---------------------------------------------------------------------------

/// Parse a JSON value into a `Vec<f64>`, handling special string values
/// ("NaN", "Inf", "-Inf") and scalar/array formats.
pub fn parse_f64_data(value: &serde_json::Value) -> Vec<f64> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(parse_f64_value).collect(),
        serde_json::Value::Number(n) => vec![n.as_f64().unwrap()],
        serde_json::Value::String(s) => vec![parse_f64_special(s)],
        _ => panic!("unexpected data format: {value}"),
    }
}

/// Parse a single JSON value to f64.
pub fn parse_f64_value(v: &serde_json::Value) -> f64 {
    match v {
        serde_json::Value::Number(n) => n.as_f64().unwrap(),
        serde_json::Value::String(s) => parse_f64_special(s),
        _ => panic!("unexpected value: {v}"),
    }
}

fn parse_f64_special(s: &str) -> f64 {
    match s {
        "NaN" => f64::NAN,
        "Inf" | "Infinity" => f64::INFINITY,
        "-Inf" | "-Infinity" => f64::NEG_INFINITY,
        other => other
            .parse::<f64>()
            .unwrap_or_else(|_| panic!("cannot parse '{other}' as f64")),
    }
}

/// Parse a JSON value into a `Vec<f32>`.
pub fn parse_f32_data(value: &serde_json::Value) -> Vec<f32> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(|v| parse_f64_value(v) as f32).collect(),
        serde_json::Value::Number(n) => vec![n.as_f64().unwrap() as f32],
        serde_json::Value::String(s) => vec![parse_f64_special(s) as f32],
        _ => panic!("unexpected data format: {value}"),
    }
}

/// Parse complex data from `[{"re": ..., "im": ...}, ...]` format.
pub fn parse_complex_data(value: &serde_json::Value) -> Vec<Complex<f64>> {
    match value {
        serde_json::Value::Array(arr) => arr
            .iter()
            .map(|v| {
                let re = v["re"].as_f64().unwrap();
                let im = v["im"].as_f64().unwrap();
                Complex::new(re, im)
            })
            .collect(),
        serde_json::Value::Object(obj) => {
            let re = obj["re"].as_f64().unwrap();
            let im = obj["im"].as_f64().unwrap();
            vec![Complex::new(re, im)]
        }
        _ => panic!("unexpected complex format: {value}"),
    }
}

/// Parse a shape array from JSON (e.g., `[3, 4]`).
pub fn parse_shape(value: &serde_json::Value) -> Vec<usize> {
    value
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as usize)
        .collect()
}

/// Parse boolean array data from JSON.
pub fn parse_bool_data(value: &serde_json::Value) -> Vec<bool> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(|v| v.as_bool().unwrap()).collect(),
        _ => panic!("unexpected bool data: {value}"),
    }
}

/// Parse string array data from JSON.
pub fn parse_string_data(value: &serde_json::Value) -> Vec<String> {
    match value {
        serde_json::Value::Array(arr) => arr
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect(),
        _ => panic!("unexpected string data: {value}"),
    }
}

/// Parse integer (usize) array data from JSON.
pub fn parse_usize_data(value: &serde_json::Value) -> Vec<usize> {
    match value {
        serde_json::Value::Array(arr) => arr.iter().map(|v| v.as_u64().unwrap() as usize).collect(),
        serde_json::Value::Number(n) => vec![n.as_u64().unwrap() as usize],
        _ => panic!("unexpected usize data: {value}"),
    }
}

// ---------------------------------------------------------------------------
// Array construction from fixture data
// ---------------------------------------------------------------------------

/// Build an `Array<f64, IxDyn>` from a fixture input object
/// (expects `{"data": [...], "shape": [...], "dtype": "float64"}`).
pub fn make_f64_array(value: &serde_json::Value) -> Array<f64, IxDyn> {
    let data = parse_f64_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Build an `Array<f32, IxDyn>` from a fixture input object.
pub fn make_f32_array(value: &serde_json::Value) -> Array<f32, IxDyn> {
    let data = parse_f32_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Build an `Array<Complex<f64>, IxDyn>` from a fixture input object.
pub fn make_complex_array(value: &serde_json::Value) -> Array<Complex<f64>, IxDyn> {
    let data = parse_complex_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Build an `Array<bool, IxDyn>` from a fixture input object.
pub fn make_bool_array(value: &serde_json::Value) -> Array<bool, IxDyn> {
    let data = parse_bool_data(&value["data"]);
    let shape = parse_shape(&value["shape"]);
    Array::from_vec(IxDyn::new(&shape), data).unwrap()
}

/// Get the dtype string from a fixture input object.
pub fn get_dtype(value: &serde_json::Value) -> &str {
    value["dtype"].as_str().unwrap_or("float64")
}

/// Check if a test case should be skipped (scalar inputs, empty arrays, or
/// non-f64 dtypes for f64-only runners).
pub fn should_skip_f64(input: &serde_json::Value) -> bool {
    let dtype = get_dtype(input);
    if dtype != "float64" {
        return true;
    }
    let shape = parse_shape(&input["shape"]);
    // Skip 0-d scalars (shape=[]) — they can't be constructed as IxDyn arrays
    if shape.is_empty() {
        return true;
    }
    false
}

/// Check if the expected output is a scalar (shape=[]).
pub fn is_scalar_expected(expected: &serde_json::Value) -> bool {
    if let Some(shape) = expected.get("shape") {
        return parse_shape(shape).is_empty();
    }
    // If expected is a bare number, it's scalar
    expected.is_number()
}

// ---------------------------------------------------------------------------
// ULP comparison
// ---------------------------------------------------------------------------

/// Compute ULP distance between two f64 values.
/// Returns `None` if either value is NaN (NaN comparison is handled separately).
pub fn ulp_distance_f64(a: f64, b: f64) -> Option<u64> {
    if a.is_nan() || b.is_nan() {
        return None;
    }
    if a == b {
        return Some(0);
    }
    // Near zero: when both values are tiny (< MIN_ULP_TOLERANCE * epsilon),
    // ULP distance becomes meaningless because the values are in the noise
    // floor of the floating-point format. Use absolute tolerance instead.
    let abs_tol = MIN_ULP_TOLERANCE as f64 * f64::EPSILON;
    if a.abs() < abs_tol && b.abs() < abs_tol {
        return Some(0);
    }
    if a.signum() != b.signum() {
        // Different signs far from zero — very large ULP distance
        let a_to_zero = a.to_bits() as i64;
        let b_to_zero = b.to_bits() as i64;
        return Some(a_to_zero.unsigned_abs() + b_to_zero.unsigned_abs());
    }
    let a_bits = a.to_bits() as i64;
    let b_bits = b.to_bits() as i64;
    Some((a_bits - b_bits).unsigned_abs())
}

/// Compute ULP distance between two f32 values.
pub fn ulp_distance_f32(a: f32, b: f32) -> Option<u64> {
    if a.is_nan() || b.is_nan() {
        return None;
    }
    if a == b {
        return Some(0);
    }
    let abs_tol = 4.0 * f32::EPSILON;
    if a.abs() < abs_tol && b.abs() < abs_tol && (a - b).abs() < abs_tol {
        return Some(0);
    }
    if a.signum() != b.signum() {
        let a_to_zero = a.to_bits() as i32;
        let b_to_zero = b.to_bits() as i32;
        return Some(a_to_zero.unsigned_abs() as u64 + b_to_zero.unsigned_abs() as u64);
    }
    let a_bits = a.to_bits() as i32;
    let b_bits = b.to_bits() as i32;
    Some((a_bits - b_bits).unsigned_abs() as u64)
}

/// Assert that two f64 values match within the given ULP tolerance.
/// NaN == NaN is considered a match. Inf signs must agree.
/// Values that are both near zero (within the noise floor of f64 arithmetic)
/// are considered matching regardless of ULP distance.
pub fn assert_f64_ulp(actual: f64, expected: f64, tolerance: u64, context: &str) {
    // NaN matches NaN
    if actual.is_nan() && expected.is_nan() {
        return;
    }
    if actual.is_nan() != expected.is_nan() {
        panic!("{context}: NaN mismatch — actual={actual}, expected={expected}");
    }
    // Inf must match sign
    if actual.is_infinite() && expected.is_infinite() {
        assert_eq!(
            actual.is_sign_positive(),
            expected.is_sign_positive(),
            "{context}: infinity sign mismatch"
        );
        return;
    }
    // Both near zero: treat as matching. ULP distance is meaningless for
    // values in the noise floor (e.g. FFT DC component of a sine wave).
    let noise_floor = 1e-13;
    if actual.abs() < noise_floor && expected.abs() < noise_floor {
        return;
    }
    match ulp_distance_f64(actual, expected) {
        Some(dist) if dist <= tolerance => {}
        Some(dist) => {
            panic!(
                "{context}: ULP distance {dist} exceeds tolerance {tolerance} \
                 (actual={actual}, expected={expected})"
            );
        }
        None => {
            panic!("{context}: comparison failed (actual={actual}, expected={expected})");
        }
    }
}

/// Assert that two f32 values match within the given ULP tolerance.
pub fn assert_f32_ulp(actual: f32, expected: f32, tolerance: u64, context: &str) {
    if actual.is_nan() && expected.is_nan() {
        return;
    }
    if actual.is_nan() != expected.is_nan() {
        panic!("{context}: NaN mismatch — actual={actual}, expected={expected}");
    }
    if actual.is_infinite() && expected.is_infinite() {
        assert_eq!(
            actual.is_sign_positive(),
            expected.is_sign_positive(),
            "{context}: infinity sign mismatch"
        );
        return;
    }
    match ulp_distance_f32(actual, expected) {
        Some(dist) if dist <= tolerance => {}
        Some(dist) => {
            panic!(
                "{context}: ULP distance {dist} exceeds tolerance {tolerance} \
                 (actual={actual}, expected={expected})"
            );
        }
        None => {
            panic!("{context}: comparison failed (actual={actual}, expected={expected})");
        }
    }
}

/// Compare two f64 slices element-by-element within ULP tolerance.
pub fn assert_f64_slice_ulp(actual: &[f64], expected: &[f64], tolerance: u64, case_name: &str) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "case '{case_name}': length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_f64_ulp(
            a,
            e,
            tolerance,
            &format!("case '{case_name}' [element {i}]"),
        );
    }
}

/// Compare two complex f64 slices element-by-element within ULP tolerance.
/// Each component (real and imaginary) is compared independently.
pub fn assert_complex_slice_ulp(
    actual: &[Complex<f64>],
    expected: &[Complex<f64>],
    tolerance: u64,
    case_name: &str,
) {
    assert_eq!(
        actual.len(),
        expected.len(),
        "case '{case_name}': length mismatch ({} vs {})",
        actual.len(),
        expected.len()
    );
    for (i, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        assert_f64_ulp(
            a.re,
            e.re,
            tolerance,
            &format!("case '{case_name}' [element {i}].re"),
        );
        assert_f64_ulp(
            a.im,
            e.im,
            tolerance,
            &format!("case '{case_name}' [element {i}].im"),
        );
    }
}

// ---------------------------------------------------------------------------
// Generic test runners
// ---------------------------------------------------------------------------

/// Run a unary f64 oracle test: `fn(Array<f64>) -> Array<f64>`.
///
/// Iterates over all f64 test cases in the fixture, constructs the input,
/// calls the function, and compares the output to the expected values.
pub fn run_unary_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<Array<f64, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        let data = parse_f64_data(&input["data"]);
        if data.is_empty() && shape == [0] {
            continue;
        }
        let arr = Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape), data).unwrap();
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_f64_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run a binary f64 oracle test: `fn(Array<f64>, Array<f64>) -> Array<f64>`.
///
/// Expects inputs "a" and "b" in the fixture.
pub fn run_binary_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>, &Array<f64, IxDyn>) -> FerrayResult<Array<f64, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input_a = &case.inputs["a"];
        let input_b = &case.inputs["b"];
        if should_skip_f64(input_a) {
            continue;
        }
        let shape_a = parse_shape(&input_a["shape"]);
        let shape_b = parse_shape(&input_b["shape"]);
        if shape_a.is_empty() || shape_b.is_empty() {
            continue;
        }
        // Skip broadcast cases — ferray uses separate _broadcast functions
        if shape_a != shape_b {
            continue;
        }
        let arr_a =
            Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape_a), parse_f64_data(&input_a["data"]))
                .unwrap();
        let arr_b =
            Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape_b), parse_f64_data(&input_b["data"]))
                .unwrap();
        let result = func(&arr_a, &arr_b)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_f64_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run a unary oracle that returns a boolean array (isnan, isinf, isfinite, signbit).
pub fn run_unary_bool_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<Array<bool, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let data = parse_f64_data(&input["data"]);
        if data.is_empty() && shape == [0] {
            continue;
        }
        let arr = Array::<f64, IxDyn>::from_vec(IxDyn::new(&shape), data).unwrap();
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_bool_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_eq!(
            result_slice.len(),
            expected.len(),
            "case '{}': length mismatch",
            case.name
        );
        for (i, (&a, &e)) in result_slice.iter().zip(expected.iter()).enumerate() {
            assert_eq!(
                a, e,
                "case '{}' [element {i}]: actual={a}, expected={e}",
                case.name
            );
        }
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run an oracle test for a function that reduces to a scalar: `fn(Array) -> f64`.
pub fn run_scalar_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<f64>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_value(&case.expected["data"]);
        assert_f64_ulp(
            result,
            expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &format!("case '{}'", case.name),
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run oracle for a reduction that returns IxDyn (could be scalar or array).
/// The function takes `(array, Option<axis>)`.
pub fn run_reduction_f64_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>, Option<usize>) -> FerrayResult<Array<f64, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        if should_skip_f64(input) {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let axis = case
            .inputs
            .get("axis")
            .and_then(|v| v.as_u64())
            .map(|v| v as usize);
        let result = func(&arr, axis)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected_data = parse_f64_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_f64_slice_ulp(
            result_slice,
            &expected_data,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no f64 test cases found in {}", path.display());
}

/// Run oracle for a complex FFT: real input -> complex output.
pub fn run_real_to_complex_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<Array<Complex<f64>, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        let dtype = get_dtype(input);
        if dtype != "float64" {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_complex_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_complex_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    // Some fixtures may have only complex inputs, so don't assert tested > 0
    let _ = tested;
}

/// Run oracle for a complex->complex FFT.
pub fn run_complex_to_complex_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<Complex<f64>, IxDyn>) -> FerrayResult<Array<Complex<f64>, IxDyn>>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["x"];
        let dtype = get_dtype(input);
        // Accept both real and complex inputs
        let arr = if dtype == "complex128" {
            make_complex_array(input)
        } else if dtype == "float64" {
            // Convert real to complex with zero imaginary
            let data = parse_f64_data(&input["data"]);
            let shape = parse_shape(&input["shape"]);
            let complex_data: Vec<Complex<f64>> =
                data.into_iter().map(|r| Complex::new(r, 0.0)).collect();
            Array::from_vec(IxDyn::new(&shape), complex_data).unwrap()
        } else {
            continue;
        };
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_complex_data(&case.expected["data"]);
        let result_slice = result.as_slice().unwrap();
        assert_complex_slice_ulp(
            result_slice,
            &expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &case.name,
        );
        tested += 1;
    }
    assert!(tested > 0, "no test cases found in {}", path.display());
}

/// Run oracle for a matrix->scalar operation (det, trace, etc.).
pub fn run_matrix_scalar_oracle<F>(path: &Path, func: F)
where
    F: Fn(&Array<f64, IxDyn>) -> FerrayResult<f64>,
{
    let suite = load_fixture(path);
    let mut tested = 0;
    for case in &suite.test_cases {
        let input = &case.inputs["a"];
        let dtype = get_dtype(input);
        if dtype != "float64" {
            continue;
        }
        let shape = parse_shape(&input["shape"]);
        if shape.is_empty() {
            continue;
        }
        let arr = make_f64_array(input);
        let result = func(&arr)
            .unwrap_or_else(|e| panic!("case '{}': function returned error: {e}", case.name));
        let expected = parse_f64_value(&case.expected["data"]);
        assert_f64_ulp(
            result,
            expected,
            case.tolerance_ulps.max(MIN_ULP_TOLERANCE),
            &format!("case '{}'", case.name),
        );
        tested += 1;
    }
    assert!(tested > 0, "no test cases found in {}", path.display());
}
